<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Email Provider</title>
    </head>
    <body>
        <div class="container">
            <h1>No find mailType!! Check your emailTemplates.</h1>
        </div>
    </body>
</html>
